version: "3.8"

services:
  paimon:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: paimon_assist
    privileged: true
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /var/run/pulse:/var/run/pulse
      - ../models:/workdir/models
      - ../recordings:/workdir/recordings
      - ../.env:/workdir/.env:ro
      - ../memory.md:/workdir/memory.md
      - ../models/tts_cache:/workdir/models/tts_cache
    environment:
      - PULSE_RUNTIME_PATH=/var/run/pulse
    ports:
      - "8160:8160"
    restart: unless-stopped
